apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: kir-k8s
  region: eu-central-1

nodeGroups:
  - name: worker-group
    instanceType: t3.micro
    desiredCapacity: 2
    privateNetworking: true
