apiVersion : apps/v1
kind: Deployment
metadata:
  name: my-web-deployment1
  labels:
    app   : my-k8s-application
    env   : prod
    owner : IvanIvan
spec:
  replicas: 2
  selector:
    matchLabels:
      project: replica
  template:
    metadata:
      labels:
        project: replica
    spec:
      containers:
        - name : replica-web
          image: kirillqq20/linux_php_apache:latest
          ports:
            - containerPort: 80

